LojaRazor/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LojaRazor.Models
{
    public class Categoria
    {
        public string Nome { get; set; }

        public Categoria(string nome)
        {
            this.Nome = nome;
        }
    }
}

LojaRazor/Models/Departamento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public class Departamento
    {
        public string Nome { get; set; }

        public IList<Categoria> Categorias { get; set; }

        public Departamento()
        {
            Categorias = new List<Categoria>();
        }
    }
}

LojaRazor/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public class Produto
    {
        
        public string Nome { get; set; }

        public string Descricao { get; set; }

        public decimal Preco { get; set; }

        public Produto(string nome, string descricao, decimal preco)
        {
            this.Nome = nome;
            this.Descricao = descricao;
            this.Preco = preco;
        }
    }
}

LojaRazor/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public class Usuario
    {
        [Required]
        public String Nome { get; set; }

        [Required, EmailAddress]
        public String Email { get; set; }

        [Required, MinLength(3)]
        public String Senha { get; set; }

        [Required]
        public DateTime DataDeNascimento { get; set; }

        [Required]
        public String Endereco { get; set; }

        public String Complemento { get; set; }

        [Required, RegularExpression("\\d{5}-\\d{3}")]
        public String CEP { get; set; }

        public string Observacoes { get; set; }

        public bool RecebePromocoes { get; set; }
    }
}

LojaRazor/Controllers/AutenticacaoController.cs
using LojaRazor.DAO;
using LojaRazor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class AutenticacaoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Autentica(string email, string senha)
        {
            UsuariosDAO dao = new UsuariosDAO();
            Usuario usuarioLogado = dao.Busca(email, senha);
            if (usuarioLogado != null)
            {
                Session["usuarioLogado"] = usuarioLogado.Nome;
                return RedirectToAction("Index", "Home");
            }
            return View("Index");
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

LojaRazor/Controllers/HomeController.cs
using LojaRazor.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {            
            ProdutosDAO produtosDAO = new ProdutosDAO();
            ViewBag.Produtos = produtosDAO.Ofertas();
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contato()
        {
            return View();
        }
    }
}

LojaRazor/Controllers/MenuController.cs
using LojaRazor.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Menu/

        public ActionResult Index()
        {
            DepartamentosDAO departamentosDAO = new DepartamentosDAO();
            ViewBag.Departamentos = departamentosDAO.Lista();
            return View();
        }

    }
}

LojaRazor/Controllers/UsuariosController.cs
using LojaRazor.DAO;
using LojaRazor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class UsuariosController : Controller
    {
        public ActionResult Form(string email)
        {
            Usuario u = new Usuario()
            {
                Email = email
            };
            return View(u);
        }

        public ActionResult Cadastra(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                UsuariosDAO dao = new UsuariosDAO();
                dao.Adiciona(usuario);
                Session["usuarioLogado"] = usuario.Nome;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("Form", usuario);
            }
        }

    }
}

LojaRazor/Views/Autenticacao/Index.cshtml
<div class="hero-unit span6">

    <h2>Login</h2>

    <p>Já Possui Cadastro? Então faça seu login</p>
    <form action="@Url.Action("Autentica", "Autenticacao")">
        <input type="text" class="input-block-level" placeholder="E-mail" required/>

        <input type="password" class="input-block-level" placeholder="Senha" required/>

        <input type="submit" class="btn btn-large btn-primary" value="Fazer Login" />
    </form>
</div>

<div class="hero-unit span6">
    <h2>Novo Usuário?</h2>

    <p>Se você ainda não tem um cadastro, informe qual é o e-mail que você deseja associar com sua conta</p>

    <form action="@Url.Action("Form", "Usuarios")">
        <input type="text" class="input-block-level" placeholder="E-mail" name="Email" />

        <input type="submit" class="btn btn-large btn-primary" value="Criar Conta" />
    </form>
</div>

@section Scripts{
   @Scripts.Render("~/bundles/scripts")
}

LojaRazor/Views/Home/Index.cshtml
<div class="hero-unit">
    <h2>Queima de Estoque</h2>
    <p>Promocao na secao de monitores!</p>
</div>
<div class="row-fluid">
    @foreach (var produto in ViewBag.Produtos)
    {
        <div class="span4">
            <h2>@produto.Nome</h2>
            <p>@produto.Descricao</p>
            <p>@produto.Preco</p>
        </div>
    }
</div>

LojaRazor/Views/Menu/Index.cshtml
@{
    Layout = null;
 }

<div class="sidebar-nav well">
    <ul>
        @foreach (var departamento in ViewBag.Departamentos)
        {
            <li class="nav-header">@departamento.Nome</li>
            foreach (var categoria in departamento.Categorias)
            {
                <li>@categoria.Nome</li>
            }
        }
    </ul>
</div>

LojaRazor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Styles.Render("~/bundles/estilos")
</head>

<body>
    @Html.Partial("_MenuSuperior")

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                @Html.Action("Index", "Menu")

            </div>
            <div class="span9">
                @RenderBody()
            </div>
        </div>
    </div>

    @RenderSection("Scripts", false)
</body>
</html>

LojaRazor/Views/Shared/_MenuSuperior.cshtml
@using LojaRazor.Internacionalizacao 

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        @Html.ActionLink("Loja Razor", "Index", "Home", null, new { @class = "brand" })
        <ul class="nav">
            <li>@Html.ActionLink(Mensagens.Sobre, "About", "Home")</li>
            <li>@Html.ActionLink(Mensagens.Contato, "Contato", "Home")</li>
        </ul>
        <p class="navbar-text pull-right">
            @if (Session["usuariologado"] != null)
            {
                @Mensagens.BemVindo
                @Session["usuariologado"]
                @Html.ActionLink(Mensagens.Logout, "Logout", "Autenticacao")
            }
            else
            {
                @Mensagens.OlaVisitante
                @Html.ActionLink(Mensagens.Login, "Index", "Autenticacao");
                @Mensagens.Ou
                @Html.ActionLink(Mensagens.CadastraSe, "Form", "Usuarios")
            }
        </p>
    </div>
</div>

LojaRazor/Views/Usuarios/Form.cshtml
@model LojaRazor.Models.Usuario
@using (Html.BeginForm("Cadastra", "Usuarios", FormMethod.Post))
{
    <fieldset>
        <legend>Dados Pessoais</legend>


        @Html.LabelFor(usuario => usuario.Nome, "Nome:")
        @Html.TextBoxFor(usuario => usuario.Nome)
        @Html.ValidationMessageFor(usuario => usuario.Nome)

        @Html.LabelFor(u => u.Email, "Email:")
        @Html.TextBoxFor(u => u.Email)
        @Html.ValidationMessageFor(u => u.Email)

        @Html.LabelFor(u => u.Senha, "Senha:")
        @Html.PasswordFor(u => u.Senha)
        @Html.ValidationMessageFor(u => u.Senha)

        @Html.LabelFor(u => u.DataDeNascimento, "Data de Nascimento:")
        @Html.TextBoxFor(u => u.DataDeNascimento)
        @Html.ValidationMessageFor(u => u.DataDeNascimento)
        
    </fieldset>

    <fieldset>
        <legend>Dados de Entrega</legend>

        @Html.LabelFor(u => u.Endereco, "Endereço:")
        @Html.TextBoxFor(u => u.Endereco)
        @Html.ValidationMessageFor(u => u.Endereco)

        @Html.LabelFor(u => u.Complemento, "Complemento:")
        @Html.TextBoxFor(u => u.Complemento)
        @Html.ValidationMessageFor(u => u.Complemento)

        @Html.LabelFor(u =>  u.CEP, "CEP:")
        @Html.TextBoxFor(u => u.CEP)
        @Html.ValidationMessageFor(u => u.CEP)

        @Html.LabelFor(u => u.Observacoes, "Observações:")
        @Html.TextAreaFor(u => u.Observacoes)
        @Html.ValidationMessageFor(u => u.Observacoes)
    </fieldset>
    <div>

        @Html.CheckBoxFor(u => u.RecebePromocoes)
        Desejo receber informações sobre promoções
    </div>

    <input type="submit" value="Cadastrar" class="btn btn-large" />
}